### ISSUE TITLE
probeer custom properties voor meer dan alleen kleur te gebruiken

### ISSUE THREAD

**Issue by lisagjh** [yujing-student/the-startup-responsive-interactieve-website#10]
Goed dat je custom properties gebruikt, probeer ze ook voor andere dingen te gebruiken zoals bijvoorbeeld padding en margin. 

https://github.com/yujing-student/the-startup-responsive-interactieve-website/blob/35ffbb3998d239076d4714e8d58367e9590cda77/styles/style.css#L20-L25

**Comment by yujing-student** [comment]
Dit heb ik gedaan

https://github.com/yujing-student/the-startup-responsive-interactieve-website/blob/22db7ac1b67358e483b52674f64dea6e6e97eabf/styles/styles.css#L28-L29
