### ISSUE TITLE
Goede Accessibilty

### ISSUE THREAD

**Issue by lisagjh** [yujing-student/the-startup-responsive-interactieve-website#11]
goede accesiibility!! lekker

<img width="570" alt="Scherm­afbeelding 2024-01-19 om 11 04 59" src="https://github.com/yujing-student/the-startup-responsive-interactieve-website/assets/131701505/4ae75e61-e246-48ae-9fc2-9ff68f89a401">

**Comment by yujing-student** [comment]
bedankt voor het compliment
