### ISSUE TITLE
op 580px screen width verdwijnt het hele menu

### ISSUE THREAD

**Issue by lisagjh** [yujing-student/the-startup-responsive-interactieve-website#12]
Hier is het hele menu weg op een of andere manier. 

<img width="570" alt="Scherm­afbeelding 2024-01-19 om 11 05 54" src="https://github.com/yujing-student/the-startup-responsive-interactieve-website/assets/131701505/d450c204-a947-4ac8-a8bf-c52d310eee7a">

Ik denk dat het te maken heeft met deze media queries. Kijk hier nog even naar.

https://github.com/yujing-student/the-startup-responsive-interactieve-website/blob/35ffbb3998d239076d4714e8d58367e9590cda77/styles/style.css#L233-L312

**Comment by yujing-student** [comment]
![image](https://github.com/yujing-student/the-startup-responsive-interactieve-website/assets/100352887/45c37e82-bf7a-4fb9-88a9-d54a097da3cb)
dit heb ik opgelost
