### ISSUE TITLE
HTML Validator: search als kind van section

### ISSUE THREAD

**Issue by Annevd** [yujing-student/the-startup-responsive-interactieve-website#13]
![image](https://github.com/yujing-student/the-startup-responsive-interactieve-website/assets/144004647/69f1330f-fd5c-46fd-a8bd-bc713b56dfb0)

Je hebt een ```<search>``` element als kind van een ```<section>``` element, in deze context mag dat niet.
Kijk of je hier een ander element kan gebruiken of misschien buiten het ```<section>``` element kan zetten.

Hier kan je nog meer lezen over het ```<section>``` element:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section

**Comment by yujing-student** [comment]
Dit heb ik gedaan door de search in de main te zetten en niet in een section
https://github.com/yujing-student/the-startup-responsive-interactieve-website/blob/12c55c212cb0edb009d79909fade77e03c8eff48/index.html#L181-L188
