### ISSUE TITLE
html semantiek

### ISSUE THREAD

**Issue by Annevd** [yujing-student/the-startup-responsive-interactieve-website#14]
https://github.com/yujing-student/the-startup-responsive-interactieve-website/blob/35ffbb3998d239076d4714e8d58367e9590cda77/index.html#L216-L235

Je maakt in je html veel gebruik van ```<div>``` elementen, misschien kan je nog controleren welke écht nodig zijn en welke je misschien kan veranderen naar een semantischer html element.

Jij kent natuurlijk je code beter dan ik dus kijk maar of dit van toepassing is!

**Comment by yujing-student** [comment]
https://github.com/yujing-student/the-startup-responsive-interactieve-website/blob/1fca8f1dae00956739a158e840a331aa4dd38269/index.html#L246-L258
dit heb ik met grid opgelost
