### ISSUE TITLE
responsive

### ISSUE THREAD

**Issue by xxdaniquee** [yujing-student/the-startup-responsive-interactieve-website#3]
https://github.com/yujing-student/the-startup-responsive-interactieve-website/blob/42086893cdbf6af184ed6c6e355fa4c92c921ec9/index.html#L168C24-L218C30

Dit is het enige stukje met tekst die niet helemaal lekker responsive mee gaat. Ik zou nog even gaan kijken naar de css voor dit stukje

**Comment by yujing-student** [comment]
ja dat klopt ik was nog niet zover met de css om dat aan te passen en dit heb ik gedaan
mobiel scherm
<img width="266" alt="image" src="https://github.com/yujing-student/the-startup-responsive-interactieve-website/assets/100352887/3f4ba0f3-bcf8-4fb7-b8d9-f184e1200f12">

voor ipad:
<img width="423" alt="image" src="https://github.com/yujing-student/the-startup-responsive-interactieve-website/assets/100352887/2751b8c1-2e2f-4b85-b5cf-a2d926558450">

voor desktop:
<img width="568" alt="image" src="https://github.com/yujing-student/the-startup-responsive-interactieve-website/assets/100352887/535ccac4-2587-4896-9476-c7d3f1975a67">
