### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by xxdaniquee** [yujing-student/the-startup-responsive-interactieve-website#4]
https://github.com/yujing-student/the-startup-responsive-interactieve-website/blob/42086893cdbf6af184ed6c6e355fa4c92c921ec9/index.html#L163C21-L166C44

Krijn heeft mij verteld over het 'search' element. Voor jou in dit geval ook handig 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/search

**Comment by yujing-student** [comment]
Bedankt voor de tip dit heb ik toegepast in mijn code
https://github.com/yujing-student/the-startup-responsive-interactieve-website/blob/b0c6fa9d392d30d328b830784d062f2c5cafdb7e/index.html#L166-L173
