### ISSUE TITLE
foto probleem

### ISSUE THREAD

**Issue by Vikkeyeftimov** [yujing-student/the-startup-responsive-interactieve-website#5]
Je indeling met foto's is nog niet goed,
dus de images beter plaatsen door bijvoorbeeld margin te veranderen en inset toe te voegen, en misschien de padding veranderen.
en dat geldt ook voor je navbar.
![image](https://github.com/yujing-student/the-startup-responsive-interactieve-website/assets/144008940/1cd538df-c226-4518-b7ef-b67c50630042)

**Comment by yujing-student** [comment]
<img width="599" alt="image" src="https://github.com/yujing-student/the-startup-responsive-interactieve-website/assets/100352887/1e37dce7-8f8c-419c-a329-0032b93d7336">
margin heb ik probleem opgelost
