### ISSUE TITLE
Search element in section

### ISSUE THREAD

**Issue by BibekMA** [yujing-student/the-startup-responsive-interactieve-website#7]
De search tag hoort in deze context niet in een section te staan. Mischien is het mogelijk om hem eruit te halen en te bekijken waar die wel goed staat

- line 142 

https://github.com/yujing-student/the-startup-responsive-interactieve-website/blob/35ffbb3998d239076d4714e8d58367e9590cda77/index.html#L142

**Comment by yujing-student** [comment]
dit heb ik gedaan door hem in de main te zetten 

https://github.com/yujing-student/the-startup-responsive-interactieve-website/blob/12c55c212cb0edb009d79909fade77e03c8eff48/index.html#L181-L188
