### ISSUE TITLE
search element mag niet in section

### ISSUE THREAD

**Issue by lisagjh** [yujing-student/the-startup-responsive-interactieve-website#9]
De HTML validator geeft aan dat een search element niet als child van een section element mag. 

https://github.com/yujing-student/the-startup-responsive-interactieve-website/blob/35ffbb3998d239076d4714e8d58367e9590cda77/index.html#L139-L150

![afbeelding](https://github.com/yujing-student/the-startup-responsive-interactieve-website/assets/131701505/2fdcad46-1e57-4ed0-8938-0d52a4fae377)

Misschien heb je hier iets aan:

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/search

**Comment by yujing-student** [comment]
Ik heb hem verplaatst naar de main zodat die niet in een section staat
https://github.com/yujing-student/the-startup-responsive-interactieve-website/blob/12c55c212cb0edb009d79909fade77e03c8eff48/index.html#L181-L188
